require("plugins")
require("settings")
require("keybindings")
require("lv-utils")
-- require("lv-treesitter")
require("lv-telescope")
require("lv-git")
require("lv-compe")
require("lv-autopairs")
require("lv-flutter-tools")
require("lv-lspinstall")
require("lv-neoformat")
require("lv-statusline")
require("lv-harpoon")
require("lv-comment")
require("lv-gitsigns")
-- require("lv-nvimtree")

require("lsp")
require("lsp.languages.python")
require("lsp.languages.typescript")
require("lsp.languages.sumneko")
-- require"lsp.languages.dart"
require("lsp.languages.efm")
require("lsp.languages.bash")
